#!/usr/bin/python
import prman


def drawTeapot(ri, x=0, y=0, z=0, rx=-90.0, ry=45.0, rz=0.0, sx=0.2, sy=0.2, sz=0.2):
    ri.TransformBegin()
    ri.Translate(x, y, z)
    ri.Rotate(ry, 0, 1, 0)
    ri.Rotate(rx, 1, 0, 0)
    ri.Scale(sx, sy, sz)
    ri.Geometry("teapot")
    ri.TransformEnd()


def drawCube(ri, x=0, y=0, z=0, rx=-90.0, ry=45.0, rz=0.0, sx=0.2, sy=0.2, sz=0.2):
    ri.TransformBegin()
    ri.Translate(x, y, z)
    ri.Rotate(ry, 0, 1, 0)
    ri.Rotate(rx, 1, 0, 0)
    ri.Scale(sx, sy, sz)
    w = 0.5
    h = 0.5
    d = 0.5
    ri.ArchiveRecord(ri.COMMENT, "Cube Generated by Cube Function")
    # rear
    face = [-w, -h, d, -w, h, d, w, -h, d, w, h, d]
    ri.Patch("bilinear", {"P": face})
    # front
    face = [w, -h, -d, w, h, -d, -w, -h, -d, -w, h, -d]
    ri.Patch("bilinear", {"P": face})
    # left
    face = [-w, -h, -d, -w, h, -d, -w, -h, d, -w, h, d]
    ri.Patch("bilinear", {"P": face})
    # right
    face = [w, -h, d, w, h, d, w, -h, -d, w, h, -d]
    ri.Patch("bilinear", {"P": face})
    # bottom
    face = [w, -h, d, w, -h, -d, -w, -h, d, -w, -h, -d]
    ri.Patch("bilinear", {"P": face})
    # top
    face = [-w, h, d, -w, h, -d, w, h, d, w, h, -d]
    ri.Patch("bilinear", {"P": face})
    ri.ArchiveRecord(ri.COMMENT, "--End of Cube Function--")

    ri.TransformEnd()
